export let produtosDados = [
  { nome: 'Arroz', marca: 'Tio João', preco: '13,99', quantidade: '5kg', mercado: 'Tauste' },
  { nome: 'Arroz', marca: 'Pateko', preco: '12,49', quantidade: '5kg', mercado: 'Superbom' },
  { nome: 'Feijão', marca: 'Camil', preco: '7,89', quantidade: '1kg', mercado: 'Confianca' },
  { nome: 'Farinha', marca: 'Dona Benta', preco: '5,49', quantidade: '1kg', mercado: 'Tauste' },
  { nome: 'macarrão', marca: 'Renata', preco: '9,90', quantidade: '500g', mercado: 'Superbom' },
  { nome: 'macarrão', marca: 'Barilla', preco: '10,90', quantidade: '500g', mercado: 'Confianca' },
  { nome: 'macarrão', marca: 'Galo', preco: '11,90', quantidade: '500g', mercado: 'Tauste' },
  { nome: 'Arroz', marca: 'Tio João', preco: '14,99', quantidade: '5kg', mercado: 'Superbom' },
  { nome: 'Feijão', marca: 'Camil', preco: '7,89', quantidade: '1kg', mercado: 'Confianca' },
  { nome: 'Feijão', marca: 'Kicaldo', preco: '8,10', quantidade: '1kg', mercado: 'Tauste' },
  { nome: 'Farinha', marca: 'Dona Benta', preco: '5,29', quantidade: '1kg', mercado: 'Superbom' },
  { nome: 'macarrão', marca: 'Renata', preco: '8,90', quantidade: '500g', mercado: 'Tauste' },
  { nome: 'macarrão', marca: 'Barilla', preco: '9,50', quantidade: '500g', mercado: 'Confianca' },
  { nome: 'macarrão', marca: 'Galo', preco: '10,00', quantidade: '500g', mercado: 'Superbom' },
];
